export { default as Login } from './Login';
export { default as Admin } from './Admin';
export { default as Caja } from './Caja';
export { default as AjusteInventario } from './AjusteInventario/AjusteInventario';
export { default as PrivateRoute } from './PrivateRoute';
export { default as HistorialVentas } from './HistorialVentas/HistorialVentas';
export { default as ReporteVentas } from './ReporteVentas/ReporteVentas';
export { default as CrudCategorias} from './CategoriaTable';
export { default as RegistrarVenta} from './RegistroVentas/RegistrarVenta';
export { default as NotFoundPage} from './NotFoundPage';
export * from './Gastos';